version: '3'
services:
  app:
    image: bitnami/laravel:latest
    container_name: aiko_api_app
    restart: always
    environment:
      - APP_KEY=${APP_KEY}
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=aikocare-db # Ganti kalo beda
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/app # Ini nih yang bikin kodingan lo masuk ke dalem
    ports:
      - "8000:8000"
    networks:
      - web-gateway

networks:
  web-gateway:
    external: true