version: '3.8'

services:
  app:
    image: bitnami/laravel:latest
    container_name: aiko_api_app
    user: root
    restart: always
    environment:
      - APP_KEY=${APP_KEY}
      - DB_HOST=aiko_mysql
      - DB_DATABASE=api_aiko
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - "8001:8000"
    # KITA PAKSA CLONE MANUAL DI DALEM CONTAINER BIAR PASTI ADA FILENYA!
    entrypoint: [ "/bin/bash", "-c", "git clone https://github.com/AbdulRozaq345/AikoCare_API.git . && composer install && php artisan key:generate && php artisan serve --host=0.0.0.0 --port=8000" ]
    networks:
      - web-gateway
      - db-network

networks:
  web-gateway:
    external: true
  db-network:
    external: true
    name: aikocare-db_default